### ISSUE TITLE
Support annotations for securitycontext user config

### ISSUE THREAD

**Issue by aweiteka** [banzaicloud/bank-vaults#116]
**Describe the bug**
Vault wants to run as uid 1000. OpenShift by default assigns a random UID in a much higher range, e.g. `uid=1000810000 gid=0(root) groups=1000810000`. This causes [docker-entrypoint.sh script](https://github.com/hashicorp/docker-vault/blob/master/0.X/docker-entrypoint.sh) to fail with

```
Could not chown /vault/config (may not have appropriate permissions)
chown: /vault/config/local.json: Operation not permitted
chown: /vault/config: Operation not permitted
chown: /vault/config: Operation not permitted
chown: /vault/file: Operation not permitted
chown: /vault/file: Operation not permitted
```

In order to get vault to run as uid 1000 we can annotate the pod spec (statefulset in this case?), e.g.

```
metadata:
  annotations: 
    openshift.io/sa.scc.uid-range: 1000/10000
```

Normally we could do this manually but the spec is hard-coded in the operator.

**The ask**: expose a parameter to customize annotations metadata.

**To Reproduce**
1. run vault operator on OpenShift

**Expected behavior**
Run as uid vault expects

**Comment by aweiteka** [comment]
cc @wshearn

**Comment by matyix** [comment]
@aweiteka @wshearn 

Thanks for reporting this - we have opened a [PR](#118) supporting specifying annotations as requested. We have tested on upstream K8s but not OpenShift. I reckon it should be working there as well - please report back if this is what you expected.

**Comment by matyix** [comment]
@aweiteka Merging the PR closed the issue - I am reopening it awaiting your confirmation that this is what you have expected and works on OpenShift.

**Comment by aweiteka** [comment]
> @aweiteka Merging the PR closed the issue - I am reopening it awaiting your confirmation that this is what you have expected and works on OpenShift.

Thanks, @matyix. I'm using the 'master' tag, updated the vault service annotation. It annotates the statefulset. Still seeing permissions issues so I'm working through the depths of SCC to make sure I'm using it correctly. I'll post back here when I know for sure.

Thanks again for the awesome response!

**Comment by matyix** [comment]
Thx @aweiteka - please let us know if there are other issues and need more changes/fixes.

**Comment by aweiteka** [comment]
Here's where I am: the annotation affects the statefulset template but the pod doesn't get this annotation and the vault container continues to runs as the incorrect user. I'm not yet clear if this is a failure of mine (not using annotations correctly) or OpenShift or the vault operator. Pasting here for your review.

**Statefulset (snippet)**

```yaml
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    generation: 1
    labels:
      app: vault
      vault_cr: vault
    name: vault
    namespace: vault
  spec:
    podManagementPolicy: OrderedReady
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: vault
        vault_cr: vault
    serviceName: ""
    template:
      metadata:
        annotations:
          openshift.io/scc: user100
        creationTimestamp: null
        labels:
          app: vault
          vault_cr: vault
      spec:
        containers:
        - args:
          - server
          - -log-level=debug
          env:
          - name: VAULT_LOCAL_CONFIG
            value: '{"api_addr":"https://vault.default:8200","listener":{"tcp":{"address":"0.0.0.0:8200","tls_cert_file":"/vault/tls/server.crt","tls_key_file":"/vault/tls/server.key"}},"storage":{"etcd":{"address":"https://etcd-cluster:2379","ha_enabled":"true","tls_ca_file":"/etcd/tls/etcd-client-ca.crt","tls_cert_file":"/etcd/tls/etcd-client.crt","tls_key_file":"/etcd/tls/etcd-client.key"}},"ui":true}'
          - name: VAULT_CACERT
            value: /vault/tls/ca.crt
          image: vault:0.10.3
          name: vault
          ports:
          - containerPort: 8200
            name: api-port
            protocol: TCP
          - containerPort: 8201
            name: cluster-port
            protocol: TCP
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
          volumeMounts:
```

**Pod (snippet)**

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: restricted
  generateName: vault-
  labels:
    app: vault
    controller-revision-hash: vault-7767ccc878
    statefulset.kubernetes.io/pod-name: vault-0
    vault_cr: vault
  name: vault-0
  namespace: vault
spec:
  containers:
  - args:
    - server
    - -log-level=debug
    env:
    - name: VAULT_LOCAL_CONFIG
      value: '{"api_addr":"https://vault.default:8200","listener":{"tcp":{"address":"0.0.0.0:8200","tls_cert_file":"/vault/tls/server.crt","tls_key_file":"/vault/tls/server.key"}},"storage":{"etcd":{"address":"https://etcd-cluster:2379","ha_enabled":"true","tls_ca_file":"/etcd/tls/etcd-client-ca.crt","tls_cert_file":"/etcd/tls/etcd-client.crt","tls_key_file":"/etcd/tls/etcd-client.key"}},"ui":true}'
    - name: VAULT_CACERT
      value: /vault/tls/ca.crt
    image: vault:0.10.3
    imagePullPolicy: IfNotPresent
    name: vault
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        drop:
        - KILL
        - MKNOD
        - NET_RAW
        - SETGID
        - SETUID
      runAsUser: 1000810000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /vault/config
      name: vault-config
    - mountPath: /vault/file
      name: vault-file
  - args:
    - --mode
    - k8s
    - --k8s-secret-namespace
    - vault
    - --k8s-secret-name
    - vault-unseal-keys
    command:
    - bank-vaults
    - unseal
    - --init
    env:
    image: banzaicloud/bank-vaults:master
    name: bank-vaults
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - NET_RAW
        - SETGID
        - SETUID
      runAsUser: 1000810000
  dnsPolicy: ClusterFirst
  hostname: vault-0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000810000
    seLinuxOptions:
      level: s0:c28,c27
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - emptyDir: {}
    name: vault-config
  - emptyDir: {}
    name: vault-file
status:
```
