### ISSUE TITLE
Unknown field "storeRootToken"

### ISSUE THREAD

**Issue by TanZng** [banzaicloud/bank-vaults#1529]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
When running 
`kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/cr.yaml`

I got this error: 
`error: error validating "https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/cr.yaml": error validating data: ValidationError(Vault.spec.unsealConfig.options): unknown field "storeRootToken" in com.banzaicloud.vault.v1alpha1.Vault.spec.unsealConfig.options; if you choose to ignore these errors, turn validation off with --validate=false`

**Expected behaviour**: 
```
vault.vault.banzaicloud.com/vault created
persistentvolumeclaim/vault-file created
```

**Steps to reproduce the bug**:
Run this commands
```
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm upgrade --install vault-operator banzaicloud-stable/vault-operator
kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/cr.yaml
```

**Additional context**:
I follow the steps from this docs but the error appear.
https://banzaicloud.com/docs/bank-vaults/operator/

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.23.1
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): -
- bank-vaults version (e.g. 0.4.17): 
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by ernadh** [comment]
You are attempting to use a feature that's to be released in 1.15. We merged the code to master which changed the example Custom Resource that won't work with previous bank-vaults versions.

Please use the following CR for your version: https://github.com/banzaicloud/bank-vaults/blob/1.14.4/operator/deploy/cr.yaml

**Comment by TanZng** [comment]
Got it thank you!

**Comment by TanZng** [comment]
I change to 1.15 version and when running the command the error still appear.

```bash
➜ kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/1.15.0/operator/deploy/cr-raft.yaml

error: error validating "https://raw.githubusercontent.com/banzaicloud/bank-vaults/1.15.0/operator/deploy/cr-raft.yaml": error validating data: ValidationError(Vault.spec.unsealConfig.options): unknown field "storeRootToken" in com.banzaicloud.vault.v1alpha1.Vault.spec.unsealConfig.options; if you choose to ignore these errors, turn validation off with --validate=false

```


```bash
➜ helm list   

NAME          	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                	APP VERSION
vault-operator	default  	1       	2022-01-31 11:16:38.068002277 -0600 CST	deployed	vault-operator-1.15.2	1.15.0     

```

**Comment by ernadh** [comment]
You're welcome!

As for docs updates, please feel free to fork and open a PR with what you think is missing and we'll gladly review.
